name: Deploy TypeDoc

on:
  push:
    branches:
      - main

jobs:
  deploy-typedoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: yarn && yarn docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: doc
